name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker Image
      run: docker build -t react-native-app .

    - name: Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/react-native-app:latest
